### ISSUE TITLE
Consistency in DiffList-Interfaces

### ISSUE THREAD

**Issue by scunz** [macgitver/libGitWrap#11]
@antis81, I just cherry-picked the two commits lingering around in libMacGitverCore's topic/ImprovedDiffList onto development and rebased my branch on top of that.

Now, I there are diffs again in MGV. However, I see at least one place (in line 105 of DiffList.cpp) where the callback is expected to return `false` for success (while you turned it around at most other places).

Could you make these consistent, please?

**Comment by antis81** [comment]
Ok, if you agree, I'll remove the topic/ImprovedDiffList branch in libMacGitverCore.

Thanks for pointing the bug out! Sorry, didn't see that. It's fixed in branch development and there's a good chance, that this was really the only place.

**Comment by scunz** [comment]
I didn't see it either when i said "ready to merge", yesterday... :-)

Of course you can remove the DiffList branch now; the less (stale) branches the better...

**Comment by scunz** [comment]
Thanks for fixing this thing so fast.

However, this brings me up to a topic that I though a few times about in the recent days: All of this code needs pretty more comments. I know that I am able to quickly dig through the deepest code-mess when most other coders would have already given up... But this libHeaven overhauling is starting to drive me crazy. There is _so_ much conceptual design buried and it's getting hard to figure it out when reading it again...

**Comment by antis81** [comment]
Well, yes. I totally agree when it comes to comments. Especially the libHeaven needs them more than any other part in MGV. Everyone hates writing comments ... until one has to dig through thousands or millions of code lines and needs to understand and often cleanup the architecture - that's a programmer's cross :smile:. So ... at least the API should be commented well. Btw.: Yesterday I was searching for the original MGV wiki - It moved along with MacGitverModules. This contains part of the docs. And ... the wiki is nothing else than a git repo. Let's bring it back to where it belongs - on the MGV repo page.

**Comment by scunz** [comment]
glad that we still have less than 50k gross lines of code... :pig:

Nice libHeaven docs... In fact, I did not even remember to have written them. So yeah, let's make them more prominent...
