### ISSUE TITLE
Cleanup file structure to improve build times

### ISSUE THREAD

**Issue by antis81** [macgitver/libGitWrap#13]
Too small classes increase build times and get more difficult to develop by the time.

Would it be ok to gather all the `...Private` class declarations and move it to `GitWrapPrivate.h`?

And for the `user manual` ... don't ever mention that there :smile:. It's a friendly agreement for developers.

**Comment by scunz** [comment]
Not the headers are increasing compile time, the many compiler invocations do.

**Comment by scunz** [comment]
> But I'm totally with you and not a fan of such "strict rules".

I'm neither a fan of such rules, but take the messy `WindowState` classes from libHeaven. I've splitted them into smaller files exactly because it is easier to develop them that way.
