### ISSUE TITLE
Naming of parts of a reference's name.

### ISSUE THREAD

**Issue by scunz** [macgitver/libGitWrap#32]
@antis81, the picture below shows a somewhat complete set of a references tree.

As you introduced the `Reference::prefix()` method, I'm asking how we should name each part of the reference name.

![ref_tree](https://f.cloud.github.com/assets/1700771/1249986/b0889176-2aeb-11e3-9625-4027e9e42593.png)

Can you give each of these lines a "name" and some named parameters how to address them? i.e.: I think for the 10th line (`refs/namespaces/foo/refs/HEAD`), it should be something like: "Current Checkout, in namespace foo".

What I'm actually trying to figure out: What methods should we implement to query a part of the ref name. Like: `Reference::namespc()` would return `foo` for the 10th line and `foo/bar` for 20th line.

**Comment by antis81** [comment]
That's a good question. Actually I used it to make the "rename ref" work. Thus, this is not fully engineered yet.

Other than the current implementation, the idea of using seperate definitions seems good to me:
- name: the full name (just a reminder :))
- prefix: the first two sections of the name ( refs/heads, refs/tags, refs/remotes, refs/... )
  Should we take three sections for remotes? ( like in refs/remotes/origin )
- namespace: everything between prefix and the last section
  ( namespaces could return a list )
- shorthand: the lg2 shorthand (unchanged)

Thus, we'd have a rule:
name = prefix + /namespace(s) + /last

Hint:
References outside this definition ( like HEAD, MERGE_HEAD, ... ) would give an empty prefix / namespace. In this case, `name` and `shorthand` would return "HEAD", ...

Any doubts anyone? :smile:

**Comment by scunz** [comment]
>  Any doubts anyone? :smile:

More than ever... I think, I will have to think a couple of hours about this and then come up with a sane concept...

However, I totally missed `refs/remotes`. Thanks for reminding me. This makes it even more complex.

**Comment by scunz** [comment]
Just an aside: How likely do you think, we will encounter name spaces on a local non-bare repository? I mean, just because I see no use case for that, doesn't mean other people don't use it locally...

**Comment by antis81** [comment]
> Just an aside: How likely do you think, we will encounter name spaces on a local non-bare repository? I mean, just because I see no use case for that, doesn't mean other people don't use it locally...

Nope, I also don't have a use case for that. Thought you'd need it :).

Leaving out namespaces will reduce that problem to remotes, locals and the HEAD refs. In case of a remote branch, the first section of the refs shorthand is always the remote name.

**Comment by scunz** [comment]
@antis81, so. I've thought a lot about this. Here's some doxygen poetry that I've come up with so far. It contains mostly no mistakes like both mine and your prior thoughts in this thread. Though, it still misses most of git's generic _notes_ features. But actually, I've read the docs for that for at least the 20th time now - and I'm still not sure I really understand how it works (At least I think that I understand what it can be used for ^^).
This is documentation for a _new_ class, not an addition to `Git::Reference`. Would be cool, if you could take a look over it (I know it's hard to understand, but it's a complex topic). This is the minimum of what I think is required to do it right; but i might have forgotten something:

References in git follow a complex to describe schemata. This class applies several rules to a reference's fully qualified name (FQRN), in order to figure out its meaning. This results in a set of parameters that can be used to qualify the reference using only the 'type' and the parameters.
For this purpose, we create the following definitions and logic to test for them:
-   _Specials_
  
  A special reference is a reference with a very special meaning inside git. We will detect: `MERGE_HEAD`, `HEAD` (wherever it occurs), `refs/stage` and the `refs/notes/commit` as such a special reference. In this case, isSpecial() will return `true`. Each of these references also has a getter method on its own: isMergeHead(), isHead(), isStage() and isCommitNote(). With the exception of `HEAD` unless it is the fully qualified reference name, further detection stops if we detect a special reference.
-   _Custom_
  
  Any regular expression can be registered with the name matcher using the registerExpression() method. If a reference name matches that expression, isCustom() will return `true` and customExpression() will return the `void*` given when the expression was registered. No further matching is performed.
  This mechanism can be used to match situation dependant special references, like GitHub's special references for the head of a pull request, which follow the regular expression: `^refs\/pull\/([1-9][0-9]*)\/head$`.
-   _Namespaced_
  
  A reference is namespaced if the regular expression:
  
  ```
  ^refs\/namespace\/([^\/]+)\/(.+)$
  ```
  
  maches at least once. If the regexp matches, `\1` will be appended to the namespaces array and the reference is replaced with `\2` and the namespace test executed again. In this case isNamespaced() will return `true`, namespaces() will return the namespace array and namespaceName() will return a string formed by joining all members of the namespace array with `/`.
-   _Remote_
  
  A reference is remote, if its FQRN starts with the `refs/remote` segments. In this case, isRemote() will return `true` and remote() will return the 3rd segment of the FQRN. The reference must match against the regular expression:
  
  ```
  ^refs\/remotes\/([^\/]+)\/(.+)$
  ```
  
  If it matches, remote() is set to `\1` and `\2` is used to perform the _Remote-Branch_ test.
-   _Remote Branch_
  
  A reference is a remote branch, if isRemote() returns `true` and `\2` from the _Remote_ case does not evaluate to `HEAD`. In this case, the Test _Scoped_ is applied to `\2`. isBranch() will return `true`. If `\2` is `HEAD`, the reference specifies the remote's default-branch-to-checkout, thus, isBranch() will return `false` but isHead() will return `true`.
-   _Local Branch_
  
  A reference is a local branch, if it starts with `refs/heads/` and the _Remote_ test did not match. In this case, isBranch() will return `true` and the _Scoped_ test will be applied using the remainder of the reference name as input.
-   _Tag_
  
  A reference is a tag, if it starts with `refs/tags/` and the _Remote_ test did not match. In this case, isTag() will return `true` and the _Scoped_ test will be applied using the remainder of the reference name as input.
-   _Scoped_
  
  The remainder as given by the _Remote_, _Local Branch_ or _Tag_ tests, is scoped, if it matches the regular expression:
  
  ```
  ^([^\/]+)\/(.+)$
  ```
  
  at least once. In this case, `\1` will be appended to the scopes array and the _Scoped_ test will be repeated with `\2`. If the regular expression does not match a single time, name() will be set to the input of the regular expression. Thus, name() will be the whole input or the string after the last `/`. If the regular expression matched at least once, isScoped() will return `true`, scopes() will return the scope array and scopeName() will return a string formed by joining all members of the scope array with `/`.
-   _Salvatory rule_
  
  If none of the above rules and tests matched the reference, we call it _peculiar_. In that case, isPeculiar() will return `true`.
-   Additional stuff
  - If isTag() returns `true`, then tagName() will return `scopeName() + '/' + name()` if isScoped() is `true` and will simply return name() if isScoped() is `false`. It will return an empty string if isTag() returns `false`.
  - If isBranch() returns `true`, then branchName() will return `scopeName() + '/' + name()` if isScoped() is `true` and will simply return name() if isScoped() is `false`. It will return an empty string if isBranch() returns `false`.

Examples:
-   `refs/heads/master`
  
  `isBranch() == true`, `name() == "master"`, `scopeName == ""`, `namespaceName() == ""`, `branchName() == "master"`
-   `refs/remotes/origin/feature/cool`
  
  `isRemote() == true`, `isBranch() == true`, `isScoped() == true`, `name() == "cool"`, `scopeName == "feature"`, `namespaceName() == ""`, `branchName() == "feature/cool"`
-   `refs/namespaces/foo/refs/namespaces/bar/refs/tags/releases/1.0`
  
  `isNamespaced() == true`, `isTag() == true`, `isScoped() == true`, `name() == "1.0"`, `scopeName == "releases"`, `namespaceName() == "foo/bar"`, `tagName() == "releases/1.0"`

**Comment by antis81** [comment]
Seems like I wasn't aware of the namespace terminology - oops ( Haven't missed it so far :smile: ).

Taking the "rename ref." use case:
Internally, we need to take the old reference name, find and replace the changed segments. Then create a new reference with the generated name.  The challenge is to create a new FQRN out of the old short name, which the user sees and changes.

**Comment by scunz** [comment]
Namespaces are used to store slightly different copies of the same repository in the same place; like `libgit2/libgit2` and `macgitver/libgit2`, where the ref `refs/tags/v0.19` in macgitver actually would be `refs/namespaces/macgitver/refs/namespaces/libgit2/refs/tags/v0.19` in libgit2. I'm not sure if GitHub really works like that. According to some blogs they've changed the storage mechanism a few times.

However, I don't think that - following my definition above - we should allow to change anything other than scope and name during a rename action.

**Comment by antis81** [comment]
> However, I don't think that - following my definition above - we should allow to change anything other than scope and name during a rename action.

Agreed.

**Comment by scunz** [comment]
Done via #33..
