### ISSUE TITLE
access the index

### ISSUE THREAD

**Issue by antis81** [macgitver/libGitWrap#9]
For further implementation of the index/stage view, we need to access the index itself to populate the `staged files list, right? Is there anything existing yet, or do we need to implement it?

If implementation is needed, I would go for a wrapper around `git_index_get_by_index`.

**Comment by scunz** [comment]
Um, well - This is a hard topic to cover... :-)

First of all, there is the [`Git::Index`](https://github.com/macgitver/libGitWrap/blob/development/libGitWrap/Index.hpp#L37-L61) class, which should do this job. As you point out correctly, it is missing accessors for the index entries themselves. So adding these wouldn't be bad - and a way to solve your problem at hand.

Secondly, if you decide to go that way, don't forget in your implementation that libgit2 itself won't bother if it has old data available. This means: You can obtain the repo's `Index` via `Repository::index()`, but make sure that before you access it, call `read()` on it.

However, when we're looking at MacGitver, we already know about the state of the index at a very prominent place. Well, few days ago I told you that I _was about to implement an index view myself for several times_ and that i _actually did not do that_. I failed in giving a reasoning for that, a leeway i have to make up now:
My initial plan was to create a working tree view, which would have been able to view the contents of the working directory alongside the already staged changes. To implement this, the work tree view is based on the `StatusHash`, which includes not only the ignore state but also files missing in work tree etc. But there is some implementation missing in work tree view (That's i.e. why files disappear as soon as you stage them). I stopped to bring this further when i realized that there is no simple way to visually distinguish _so_ many different possible states. Finally, I think with telling you that an index view is a good idea to implement, i might have made an unconscious decision to give up the idea of making a combined index/work tree view.

... and I still think we should provide separate index / work tree views _at least for now_. It is easier to implement and when we know exactly what we can display, we might be able to merge them to one view at a time.

**Comment by antis81** [comment]
Hm ... ok. Thanks for telling me about that once more. Somehow, I didn't see the idea of having the stage view within the work tree. Keeping that in mind (a.k.a setting up an issue stating that in MGV).

Still ... as you say right, it would help to get access through `Git::Index`. Thanks for the additional info about that :+1:.

**Comment by antis81** [comment]
Think we can close that one for now. We have implementations now to access the index and status information.

**Comment by scunz** [comment]
@antis81, Yep, basic index operation is possible and the status stuff turned out to be really cool.

As for manipulating the index, I don't think that MGV will require that any time soon - so it's okay to leave it for now. I'll take care of it when the need arises in my _Wookiee_ :smile:

I have some unfinished new feature for MGV in bvrgl, but I currently lack time for finishing it. It's about adding custom shell scripts in every place. I need to get [this](https://www.ohloh.net/p/bonaparte) done right now.
